language: python
services:
  - memcached
  - redis-server
python:
  - '3.6'
install:
  - pip install -e .[test,ci]
script:
  - pytest --cov=scrooge --cov-report annotate
deploy:
  skip_cleanup: true
  provider: pypi
  user: marcelomoraes28
  on:
    tags: true
    branch: master
    python: '3.6'
  password:
    secure: qMTjBMOCfIFGkYBSN7IIIN/yU5zmsZlxnGfYxkCNZJt8yl7lsqjr+H/Y8ERDUuMeMmGBMUPfDHEamh3Y5Ds05awGSC5UodHAlH3zhmBuwB5FNo8rKtVlLMYJ4TimEbjClZNqsptme2LOWbq5SUa4mhSk9UeUto5cGzXiyHtpiCL3475+ruBa1B3teez0dozavTmlR2uJ133JT9QscEWChRCGjY8jNRl1qNAIJD7+iSaOX6eRs8bvwqCM8D5EHiF/17WF6Iu8nv4XRf/dPMaoQeyngQXiqRGh+2EVDudxQsshkmIxrU8tTVaFhO/jXOljXAf6Ks2ZGmdB4w0OXlkTxZb85MhAInjG3KBZi/3j+cO492wHA9LCZLFvwIMhp8UCHwPkoZCZ745+R99VjQdRZNQWt2FVW0vNJ3hDe3iV47HOIMRNmFRy4ud+kw/+MxidS/38AFWB1BqopL45qDygVQJchVrw2L+glw2AO9moWrV/up7t8pSRQb8h22SMty92YCwf2gF5wBQMPZENe0pCBzur0lpfGFEAyRKJEiNjV9llCGp7ncStHeeNNN+pjfTRjqeyyPh5q41LwYJsKC6Ju8Siwsz6wN+kjk2t086gMwxHQTpMhtjmGwyteHneR4V8FRzWzc96JD3U8spK2m+xl0tvc8cAsnbcHbIIW12VGNg=
after_success:
- coveralls