language: python
services:
  - memcached
  - redis-server
python:
  - '3.6'
install:
  - pip install -e .[test,ci]
script:
  - pytest --cov=scrooge --cov-report annotate
deploy:
  skip_cleanup: true
  provider: pypi
  user: marcelomoraes28
  on:
    tags: true
    branch: master
    python: '3.6'
  password:
    secure: 3Nqg6HEqOdEjkYBrjMPIOMhqJVBHARHoCKzYTUV5qONryHPRZevracm0R8GOEQfXqjv2hX77mOKlWHFac9KlbL5LkAGPVzvV2DQVYmdBL7Bv2eJ7UL/uimZFzMboahKhu6uQGNXkDSHU2x1zlY972/pkO6JVZ/P+OZ6WIGsu0jluB62uyYEYn1r0i+UV13wRgbGRWqYVjpVSBhu8MgK7y7JpFDcSScnDN1T2hmYsNUBpozvBi1SX/KpBLdltbdt4EH0dHmTGk6s4Vqc4x+sA6vs2RBaFDwHgHjpezkVXPFTznNi8kfzH6jDzBXLEdu0/f/tINGh6SG+s9OlSQunofFxPO2xQOPHJR1rUd3T4lqbl3lgr+fH4XNNvsA5QD5LSq7k7IW81FBDopbbl6rQJfDYQAjsuiupQ9xZJyDNf07mQtzQ91UT58KAZnjLkiMFXe6zGPrdPqSfWZjM68IDLSPEywC8VBlrpHdSoL3rPuV2yJPjEIZX8qt+duGp5yKoBXCS3wnsFMBwaS/2DOFVY9QvqJuycaumjUc7Ps/zPRastRpYJCjBtDAyxRGtgeV5xqBNu6nwA3dUHnZbQQ0ILpIscQnFsNGcVxUtknJciNW6YKPWAbzMCRd+TvGBtb7YhRhZ6CndN1xmzHOJx8Jk+C8o77kQqxnEm+vAuMIs7+1M=
after_success:
- coveralls